include: package:effective_dart/analysis_options.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    always_declare_return_types: error
    avoid_returning_null_for_future: error
    avoid_returning_null_for_void: error
    await_only_futures: error
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error
    missing_required_param: error
    missing_return: error
    null_closures: error
    recursive_getters: error
    only_throw_errors: error
    unawaited_futures: error
    valid_regexps: error

linter:
  rules:
    # Extra lints from Effective Dart
    avoid_function_literals_in_foreach_calls: true
    prefer_typing_uninitialized_variables: true
    use_function_type_syntax_for_parameters: true

    # Lints from Flutter
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true

    # Lints from Pedantic
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    empty_catches: true
    no_duplicate_case_values: true
    null_closures: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    recursive_getters: true
    unawaited_futures: true
    unnecessary_null_in_if_null_operators: true
    unrelated_type_equality_checks: true
    valid_regexps: true

    # Custom additional lints
    avoid_bool_literals_in_conditional_expressions: true
    avoid_field_initializers_in_const_classes: true
    avoid_escaping_inner_quotes: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    cancel_subscriptions: true
    cast_nullable_to_non_nullable: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    depend_on_referenced_packages: true
    deprecated_consistency: true
    directives_ordering: true
    do_not_use_environment: true
    empty_statements: true
    exhaustive_cases: true
    file_names: true
    hash_and_equals: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_private_types_in_public_api: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_runtimeType_toString: true
    noop_primitive_operations: true
    null_check_on_nullable_type_parameter: true
    only_throw_errors: true
    overridden_fields: true
    package_names: true
    package_prefixed_library_names: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_parameters: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_inlined_adds: true
    prefer_is_not_operator: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    throw_in_finally: true
    tighten_type_of_initializing_formals: true
    unnecessary_await_in_return: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unsafe_html: true
    use_build_context_synchronously: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_string_buffers: true
    use_test_throws_matchers: true
    void_checks: true

    # Disabled lints
    avoid_private_typedef_functions: false
    avoid_types_on_closure_parameters: false
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    non_constant_identifier_names: false
    prefer_relative_imports: false
    public_member_api_docs: false
