include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-dynamic: false
  errors:
    always_declare_return_types: error
    avoid_returning_null_for_void: error
    await_only_futures: error
    null_closures: error
    recursive_getters: error
    only_throw_errors: error
    unawaited_futures: error

linter:
  rules:
    # Enabled lints
    avoid_renaming_method_parameters: true
    avoid_slow_async_io: true
    close_sinks: true
    comment_references: true
    depend_on_referenced_packages: true
    deprecated_consistency: true
    directives_ordering: true
    do_not_use_environment: true
    eol_at_end_of_file: true
    literal_only_boolean_expressions: true
    noop_primitive_operations: true
    only_throw_errors: true
    prefer_final_parameters: true
    prefer_null_aware_method_calls: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_constructors_first: true
    unawaited_futures: true
    unsafe_html: true
    use_build_context_synchronously: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late: true
    use_named_constants: true
    use_raw_strings: true
    use_test_throws_matchers: true

    # Disabled lints
    constant_identifier_names: false
    non_constant_identifier_names: false
