name: cadansa_app
description: CaDansa app

version: 1.0.0+5
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'
  flutter: '>=2.5.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^3.0.0-nullsafety.0
  built_collection: ^5.1.1
  cached_network_image: ^3.1.0
  circular_reveal_animation: ^2.0.0
  collection: ^1.15.0
  custom_refresh_indicator: ^1.0.0
  expandable: ^5.0.1
  flutter_cache_manager: ^3.1.2
  flutter_dotenv: ^5.0.2
  flutter_html: ^2.1.5
  flutter_inappwebview: ^5.3.2
  flutter_local_notifications: ^9.0.0
  format: ^1.1.1
  http: ^0.13.4
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.6295
  meta: ^1.7.0
  package_info_plus: ^1.3.0
  photo_view: ^0.13.0
  sanitize_html: ^2.0.0
  scrollable_positioned_list: ^0.2.2
  shared_preferences: ^2.0.8
  shimmer: ^2.0.0
  sprintf: ^6.0.0
  timezone: ^0.8.0
  url_launcher: ^6.0.12
  webfeed: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^3.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  test: any

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'

flutter:
  assets:
    - .env

  fonts:
    - family: AppFontFamily
      fonts:
        - asset: assets/fonts/app-font.otf
    - family: MapFontFamily
      fonts:
        - asset: assets/fonts/map-regular.otf
        - asset: assets/fonts/map-bold.otf
          weight: 700
        - asset: assets/fonts/map-light.otf
          weight: 300

  uses-material-design: true
