name: cadansa_app
description: CaDansa app

version: 3.1.1+22
publish_to: none

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: '>=3.24.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^3.0.0
  built_collection: ^5.1.1
  cached_network_image: ^3.4.1
  circular_reveal_animation: ^2.0.1
  collection: ^1.18.0
  custom_refresh_indicator: ^4.0.1
  expandable: ^5.0.1
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^17.2.3
  format: ^1.5.2
  http: ^1.2.2
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  meta: ^1.15.0
  package_info_plus: ^8.1.0
  photo_view: ^0.15.0
  rss_dart: ^1.0.10
  sanitize_html: ^2.1.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sprintf: ^7.0.0
  timezone: ^0.9.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^4.1.1
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  test: any

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'

flutter:
  assets:
    - .env
    - assets/ca/lets-encrypt-r3.pem
    - assets/images/
    - config/cadansa2019.json
    - config/cadansa2022.json
    - config/cadansa2023.json

  fonts:
    - family: AppFontFamily
      fonts:
        - asset: assets/fonts/app-font.otf
    - family: MapFontFamily
      fonts:
        - asset: assets/fonts/map-regular.otf
        - asset: assets/fonts/map-bold.otf
          weight: 700
        - asset: assets/fonts/map-light.otf
          weight: 300

  uses-material-design: true
