name: cadansa_app
description: CaDansa app

version: 1.0.0+5

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^2.1.0
  cached_network_image: ^2.5.0
  expandable: ^4.1.4
  flutter_cache_manager: ^2.1.1
  flutter_dotenv: ^3.1.0
  flutter_html: ^1.2.0
  material_design_icons_flutter: ^4.0.5855
  photo_view: ^0.10.3
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  sprintf: ^5.0.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^2.0.1
  effective_dart: ^1.3.0
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
    - .env
    - config/config.json
    - config/cadansa2019.json

  fonts:
    - family: MapFontFamily
      fonts:
        - asset: assets/fonts/map-regular.otf
        - asset: assets/fonts/map-bold.otf
          weight: 700
        - asset: assets/fonts/map-light.otf
          weight: 300

  uses-material-design: true
