name: cadansa_app
description: CaDansa app

version: 1.0.0+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^2.1.0
  expandable: ^4.1.2
  flutter_dotenv: ^2.1.0
  flutter_html: ^0.11.1
  material_design_icons_flutter: ^3.4.4895
  photo_view: ^0.9.1
  shared_preferences: ^0.5.6+1
  shimmer: ^1.0.1
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  assets:
    - .env
    - plattegrond_de_meenthe_bezoekers_EN_0-1.png

  uses-material-design: true
