name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Generate dummy resource files
        run: mkdir -p assets/fonts && touch .env assets/fonts/app-font.otf assets/fonts/map-{bold,light,regular}.otf
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: subosito/flutter-action@v2
      - run: flutter config --no-analytics --no-cli-animations
      - run: flutter pub get
      - run: flutter test
