name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate dummy resource files
        run: mkdir -p assets/fonts && touch assets/fonts/map-{bold,light,regular}.otf
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter test
